export enum EventCategory {
  CONFERENCE = 'CONFERENCE',
  WORKSHOP = 'WORKSHOP',
  MEETUP = 'MEETUP',
  CONCERT = 'CONCERT',
  FESTIVAL = 'FESTIVAL',
  WEBINAR = 'WEBINAR',
  SEMINAR = 'SEMINAR',
  PARTY = 'PARTY',
  EXHIBITION = 'EXHIBITION',
  SPORT_EVENT = 'SPORT_EVENT'
}
